# scripts/generate_examples.py
"""Generate 10 high-quality research examples for portfolio"""

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.rag.vector_store import VectorStore
from src.agents.orchestrator import AgentOrchestrator
import json
from datetime import datetime

# Example queries showcasing different capabilities
SHOWCASE_QUERIES = [
    {"query": "What are recent advances in transformer models?", "depth": "deep", "style": "technical"},
    {"query": "How does CRISPR gene editing work?", "depth": "moderate", "style": "detailed"},
    {"query": "What is reinforcement learning?", "depth": "moderate", "style": "detailed"},
    {"query": "Compare CNNs and transformers for computer vision", "depth": "deep", "style": "technical"},
    {"query": "What are the applications of quantum computing?", "depth": "moderate", "style": "detailed"},
    {"query": "How do large language models work?", "depth": "deep", "style": "technical"},
    {"query": "What is protein folding prediction?", "depth": "moderate", "style": "detailed"},
    {"query": "Explain meta-learning approaches", "depth": "moderate", "style": "detailed"},
    {"query": "What are generative adversarial networks?", "depth": "moderate", "style": "detailed"},
    {"query": "How does attention mechanism work in neural networks?", "depth": "deep", "style": "technical"}
]

def generate_examples():
    print("="*80)
    print("GENERATING 10 PORTFOLIO-QUALITY EXAMPLES")
    print("="*80)
    
    # Initialize
    vs = VectorStore()
    with open('data/papers/arxiv_papers.json', 'r') as f:
        papers = json.load(f)
    vs.add_papers(papers[:200])
    
    orch = AgentOrchestrator(vs)
    
    examples = []
    os.makedirs('examples', exist_ok=True)
    
    for i, showcase in enumerate(SHOWCASE_QUERIES, 1):
        print(f"\n[{i}/10] Generating: {showcase['query'][:50]}...")
        
        result = orch.research(
            showcase['query'],
            {'top_k': 5, 'depth': showcase['depth'], 'style': showcase['style']}
        )
        
        # Save as markdown
        md = f"""# Research Example {i}

**Query:** {showcase['query']}

**Configuration:**
- Papers analyzed: {result['papers_analyzed']}
- Depth: {showcase['depth']}
- Style: {showcase['style']}

**Quality Metrics:**
- Quality Score: {result['quality_score']:.2f}
- Completeness: {result['quality_metrics']['completeness']:.2f}
- Depth: {result['quality_metrics']['depth']:.2f}
- Coherence: {result['quality_metrics']['coherence']:.2f}

---

## Research Summary

{result['summary']}

---

## Key Papers

{chr(10).join([f'{i}. {p}' for i, p in enumerate(result['key_papers'], 1)])}

---

## Citations

{chr(10).join(result['citations'])}

---

*Generated by ARIA on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""
        
        with open(f'examples/example_{i:02d}.md', 'w') as f:
            f.write(md)
        
        examples.append({
            'query': showcase['query'],
            'quality': result['quality_score'],
            'length': len(result['summary'])
        })
        
        print(f"  ✓ Quality: {result['quality_score']:.2f} | Length: {len(result['summary'])} chars")
    
    # Summary
    print("\n" + "="*80)
    print("✅ 10 EXAMPLES GENERATED")
    print("="*80)
    avg_quality = sum(e['quality'] for e in examples) / len(examples)
    print(f"Average quality: {avg_quality:.2f}")
    print(f"Saved to: examples/example_01.md through example_10.md")
    
    return examples

if __name__ == "__main__":
    examples = generate_examples()